language: objective-c
osx_image: xcode9.2
script:
    - xcodebuild clean build -sdk iphonesimulator11.2 -project MyCards/MyCards.xcodeproj -scheme MyCards CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
    - xcodebuild test -sdk iphonesimulator11.2 -project MyCards/MyCards.xcodeproj -scheme MyCards CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
