// This class is automatically included in FastlaneRunner during build

// This autogenerated file will be overwritten or replaced during build time, or when you initialize `scan`
//
//  ** NOTE **
//  This file is provided by fastlane and WILL be overwritten in future updates
//  If you want to add extra functionality to this project, create a new file in a
//  new group so that it won't be marked for upgrade
//

class Scanfile: ScanfileProtocol {
    let project: String = "MyCards.xcodeproj"
    let scheme: String = "MyCards"
    let clean: Bool = true
    let outputTypes: String = "html"
    let devices: [String] = ["iPhone X"]
}
