disabled_rules: # rule identifiers to exclude from running
- valid_docs
- missing_docs
- type_name # Swift 3 suggests lowercase enum cases
- nesting
- trailing_comma
opt_in_rules: # some rules are only opt-in
  - empty_count
  - cyclomatic_complexity
  - closure_spacing
  - explicit_init
  - overridden_super_call
  - redundant_nil_coalesing
  - private_outlet
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - DerivedData
# binary rules can set their severity level
force_cast: warning
force_try: warning
line_length: 120
type_body_length:
  - 300 # warning
  - 400 # error
file_length:
  warning: 500
  error: 1000
function_parameter_count:
  warning: 5
  error: 6
cyclomatic_complexity:
  warning: 4
error: 6
function_body_length:
  warning: 50
  error: 200
variable_name:
  min_length: 2
  max_length: 30
